[tool.poetry]
name = "zelda game"
version = "0.1.0"
description = ""
authors = ["Nyctophilia58 <nowshingdr@protonmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
